name: Build Docker Image and Create Release

on:
  push:
    tags:
      - 'v*'  # Trigger on tag push, e.g., v1.0.0, v1.1.0, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (for advanced Docker build features)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub or GitHub Container Registry (you can choose one)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password or token

      # Build the Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME="exilio016/finbot"
          TAG_NAME="${GITHUB_REF#refs/tags/}"  # Get tag name (e.g., v1.0.0)
          docker build -t $IMAGE_NAME:$TAG_NAME .

      # Push the Docker image to Docker Hub or GitHub Container Registry
      - name: Push Docker image to Docker Hub
        run: |
          IMAGE_NAME="exilio016/finbot"
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          docker push $IMAGE_NAME:$TAG_NAME

      - name: Save docker image
        run: |
          IMAGE_NAME="exilio016/finbot"
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          docker save $IMAGE_NAME:$TAG_NAME finbot-$TAG_NAME.tar

      # Create a GitHub release
      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}  # Use the tag as the release version
          release_name: "Release ${{ github.ref }}"
          body: |
            Docker image for version ${{ github.ref }} has been created.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for release creation

      # Optionally, attach the Docker image or some other artifact to the release
      - name: Upload Docker image to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./finbot-${{ github.ref }}.tar  # Path to Docker image tar file, if you'd like to attach it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for release
